using AdventOfCode2023.SolutionsByDay.Day1;
using AdventOfCode2023.SolutionsByDay.Day2;
using AdventOfCode2023.SolutionsByDay.Day3;
using AdventOfCode2023.SolutionsByDay.Day4;
using AdventOfCode2023.SolutionsByDay.Day5;
using AdventOfCode2023.SolutionsByDay.Day6;
using AdventOfCode2023.SolutionsByDay.Day7;
using AdventOfCode2023.SolutionsByDay.Day8;
using System.Diagnostics;

// Console.WriteLine("Day 1 Part 1:" + new Day1().GetDay1Part1Solution().ToString());
// Console.WriteLine("Day 1 Part 2:" + new Day1().GetDay1Part2Solution().ToString());
// Console.WriteLine("Day 2 Part 1:" + new Day2().GetPart1Solution().ToString());
// Console.WriteLine("Day 2 Part 2:" + new Day2().GetPart2Solution().ToString());
// Console.WriteLine("Day 3 Part 1:" + new Day3().GetPart1Solution().ToString());
// Console.WriteLine("Day 3 Part 2:" + new Day3().GetPart2Solution().ToString());
// Console.WriteLine("Day 4 Part 1:" + new Day4().GetPart1Solution().ToString());
// Console.WriteLine("Day 4 Part 2:" + new Day4().GetPart2Solution().ToString());
// Console.WriteLine("Day 5 Part 1:" + new Day5().GetPart1Solution().ToString());
// Console.WriteLine("Day 5 Part 2:" + new Day5().GetPart2Solution().ToString());
// Console.WriteLine("Day 6 Part 1:" + new Day6().GetPart1Solution().ToString());
// Console.WriteLine("Day 6 Part 2:" + new Day6().GetPart2Solution().ToString());
// Console.WriteLine("Day 7 Part 1:" + new Day7().GetPart1Solution().ToString());
// Console.WriteLine("Day 7 Part 2:" + new Day7().GetPart2Solution().ToString());
// Console.WriteLine("Day 8 Part 1:" + new Day8().GetPart1Solution().ToString());
Stopwatch sw = new();
sw.Start();
Console.WriteLine("Day 8 Part 2:" + new Day8().GetPart2Solution().ToString());
sw.Stop();
Console.WriteLine("Time taken: " + sw.ElapsedMilliseconds + "ms");
